[package]
name = "cling"
version = "1.0.0"
edition = "2018"

[dependencies]
pnet = "0.25"
dnsclient = "0.1"
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0"
bincode = "1.2"
clap = "2.33"
regex = "1.3"
ctrlc = "3.0"
